version: "3.8"

services:

  mysql:
    container_name: mysql-gesoc-2020
    image: mysql:8.0
    ports:
      - 3344:3306
    volumes:
      - mysql-data-2020:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: 'bd_tp'
      MYSQL_ROOT_PASSWORD: 'mysql'
      # MYSQLD_SKIP_GRANT_TABLES: "true"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]
      start_period: 1m
      interval: 30s
      timeout: 5s
      retries: 20
    expose:
      - '3344'

  backend:
    container_name: backend-gesoc-2020
    build:
        dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - '9000'
    

volumes:
  mysql-data-2020:
  
